INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[아침몰] 바로드숑 실온보관 19종 1팩 골라담기',
       '아침몰',
       2000,
       '만두/간식',
       0.66,
       '국내산',
       0,
       0,
       'main/barodesion.jpg'); 
       
INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[아침몰] 가마솥 아침밥 9+9팩',
       '아침몰',
       35000,
       '라이스',
       0.52,
       '국내산',
       0,
       0,
       'main/achimrice.jpg'); 

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[아침몰] 바로드숑 실온보관 닭가슴살 골라담기 1+1팩',
       '아침몰',
       7000,
       '닭가슴살',
       0.57,
       '국내산',
       0,
       0,
       'main/barodesionchi.jpg'); 

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[포르미] 반칙도시락 8종8팩',
       '포르미',
       45900,
       '라이스',
       0.20,
       '국내산',
       0,
       0,
       'main/banchick.jpg'); 


INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[포르미] 인생도시락 10종10팩',
       '포르미',
       63000,
       '라이스',
       0.27,
       '국내산',
       0,
       0,
       'main/insaeng.jpg'); 

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[포르미] 더포르미 8종8팩 맛있는 영양잡곡밥 도시락',
       '포르미',
       44100,
       '라이스',
       0.23,
       '국내산',
       0,
       0,
       'main/theforme.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[포르미] 미니덮밥 8종8팩 가정식 고기덮밥 간편식 냉동도시락 ',
       '포르미',
       35400,
       '라이스',
       0.24,
       '국내산',
       0,
       0,
       'main/mini.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[프레시지] 바를정육 한입LA갈비 500g ',
       '프레시지',
        15900,
       '스테이크/큐브',
       0.25,
       '외국산',
       0,
       0,
       'main/LA.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[프레시지] 바삭튀겨나온 롱 치즈 돈까스 100g 5팩+소스증정(5팩)',
       '프레시지',
        22500,
       '만두/간식',
       0.25,
       '국내산',
       0,
       0,
       'main/longcheese.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[프레시지] theEASY 파스타 4종4팩',
       '프레시지',
        31600,
       '만두/간식',
       0.37,
       '국내산',
       0,
       0,
       'main/theeasy.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[프레시지] 우리쌀밥 즉석밥 백미 1BOX (36개입) (상온)',
       '프레시지',
        52000,
       '라이스',
       0.46,
       '국내산',
       0,
       0,
       'main/whiterice.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[허닭] 잡곡밥 도시락 6종 6팩',
       '허닭',
        33000,
       '라이스',
       0.43,
       '국내산',
       0,
       0,
       'main/mixeddosirak.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[허닭] PICK 닭가슴살 소스 스테이크 100g 3종 혼합 10팩',
       '허닭',
        23000,
       '스테이크/큐브',
       0.48,
       '외국산',
       0,
       0,
       'main/saucesteak.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[허닭] PICK 통닭다리 190g 3종 혼합 10팩 ',
       '허닭',
        41400,
       '만두/간식',
       0.54,
       '외국산',
       0,
       0,
       'main/saucesteak.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[허닭] 그릴 닭가슴살 스테이크 100g 6종 혼합 12팩',
       '허닭',
        3000    ,
       '스테이크/큐브',
       0.54,
       '국내산',
       0,
       0,
       'main/grilledsteak.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[허닭] 어묵바 80g 3종 혼합 10팩',
       '허닭',
        30000    ,
       '만두/간식',
       0.54,
       '외국산',
       0,
       0,
       'main/fishcake.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[허닭] 닭가슴살 곤약볶음밥 250g 3종 혼합 10팩',
       '허닭',
        39000,
       '라이스',
       0.50,
       '국내산',
       0,
       0,
       'main/gonyak.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[허닭] 닭가슴살 비엔나 3종 혼합 10팩',
       '허닭',
        19500,
       '만두/간식',
       0.65,
       '국내산',
       0,
       0,
       'main/brvienna.jpg');

INSERT INTO products(prod_name,
                     prod_brand,
                     prod_price,
                     prod_type,
                     prod_sale,
                     prod_from,
                     prod_stock,
                     prod_ordCnt,
                     prod_img)
VALUES('[허닭] 한입 닭가슴살 큐브 100g 6종 혼합 10팩',
       '허닭',
        25000,
       '스테이크/큐브',
       0.46,
       '국내산',
       0,
       0,
       'main/breastcube.jpg');

COMMIT;
