ALTER TABLE products
MODIFY p_sale NUMBER(10, 5);

INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('프닭 곤약 김밥 궁중잡채',
       '프레시지',
       7000,
       '라이스',
       0.21,
       '국내산',
       0,
       0,
       'pre-kimbob-jobchae.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('프닭 곤약 김밥 매콤제육',
       '프레시지',
       7000,
       '라이스',
       0.21,
       '국내산',
       0,
       0,
       'pre-kimbob-maekom.jpg');

INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('슈퍼크런치 찰핫도그',
       '프레시지',
       2000,
       '만두/간식',
       0.05,
       '외국산',
       0,
       0,
       'pre-crunch-hotdog.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('슈퍼크런치 모짜렐라 치즈핫도그',
       '프레시지',
       2500,
       '만두/간식',
       0.04,
       '외국산',
       0,
       0,
       'pre-crunch-hotdog-mo.jpg');

INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('PICK 통닭다리 블랙',
       '허닭',
       6900,
       '닭가슴살',
       0.43,
       '외국산',
       0,
       0,
       'heo-pick-leg-black.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('PICK 통닭다리 허니갈릭',
       '허닭',
       6900,
       '닭가슴살',
       0.43,
       '외국산',
       0,
       0,
       'heo-pick-leg-garic.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('중화식 구운 주먹밥 새우맛',
       '발재반점',
       2500,
       '라이스',
       0.6,
       '외국산',
       0,
       0,
       'bal-chin-griled-shrimp.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('중화식 구운 주먹밥 게살맛',
       '발재반점',
       2500,
       '라이스',
       0.6,
       '외국산',
       0,
       0,
       'bal-chin-griled-crab.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('프레시업 슬라이스 닭가슴살 오리지널',
       '허닭',
       2800,
       '닭가슴살',
       0,
       '국내산',
       0,
       0,
       'heo-slice-filet-origin.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('프레시업 슬라이스 닭가슴살 케이준',
       '허닭',
       2800,
       '닭가슴살',
       0,
       '국내산',
       0,
       0,
       'heo-slice-filet-cajun.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('크리스피 통 닭가슴살 치즈',
       '허닭',
       2900,
       '닭가슴살',
       0.14,
       '국내산',
       0,
       0,
       'heo-crispy-filet-ch.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('닭가슴살 비엔나 오리지널',
       '허닭',
       1950,
       '소시지',
       0,
       '국내산',
       0,
       0,
       'heo-filet-Vienna-origin.jpg');     
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('닭가슴살 비엔나 트리플치즈',
       '허닭',
       1950,
       '소시지',
       0,
       '국내산',
       0,
       0,
       'heo-filet-Vienna-ch.jpg'); 
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('오븐구이 닭가슴살바',
       '허닭',
       1950,
       '소시지',
       0,
       '국내산',
       0,
       0,
       'heo-oven-filetbar.jpg'); 
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('PICK 닭가슴살 소스 스테이크 데리야끼',
       '허닭',
       2500,
       '스테이크/큐브',
       0,
       '외국산',
       0,
       0,
       'heo-pick-filet-steak-deli.jpg'); 
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('그릴 닭가슴살 스테이크 깻잎',
       '허닭',
       2500,
       '스테이크/큐브',
       0,
       '외국산',
       0,
       0,
       'heo-gril-filet-steak-ggak.jpg'); 
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('한입 닭가슴살 큐브 떡갈비',
       '허닭',
       2500,
       '스테이크/큐브',
       0,
       '국내산',
       0,
       0,
       'heo-onbite-filet-cube.jpg'); 
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('스팀 닭가슴살볼 고추맛',
       '허닭',
       2500,
       '스테이크/큐브',
       0,
       '국내산',
       0,
       0,
       'heo-steam-filetball-chil.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('속보이는 얇은피 닭가슴살 만두',
       '허닭',
       2900,
       '만두/간식',
       0,
       '국내산',
       0,
       0,
       'heo-filet-dumpling.jpg');  
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('속보이는 얇은피 닭가슴살 김치만두',
       '허닭',
       2900,
       '만두/간식',
       0,
       '국내산',
       0,
       0,
       'heo-filet-dumpling-kimchi.jpg');
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('부드러운 닭가슴살 육포 스파이시',
       '허닭',
       2900,
       '만두/간식',
       0,
       '국내산',
       0,
       0,
       'heo-filet-jerky-spi.jpg'); 
       
INSERT INTO products(p_name,
                     p_brand,
                     p_price,
                     p_type,
                     p_sale,
                     p_from,
                     p_stock,
                     p_ordCnt,
                     p_img)
VALUES('쇠고기 육포 오리지널',
       '허닭',
       1500,
       '만두/간식',
       0,
       '외국산',
       0,
       0,
       'heo-beef-jerky-ori.jpg'); 
       
COMMIT;
