ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER dak
IDENTIFIED BY dak;

ALTER USER dak DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION
TO dak;

GRANT CREATE SESSION, 
      CREATE SEQUENCE,
      CREATE TABLE, 
      CREATE VIEW
TO dak;

commit;
